### ISSUE TITLE
how to import lua lib

### ISSUE THREAD

**Issue by galenzhao** [APItools/middleware#51]
when I import a redis lib

{"error":"[string \"cache redis\"]:843: attempt to call global 'require' (a nil value)"}

**Comment by mikz** [comment]
All the middleware is evaluated in a sandbox because it was meant to be run on shared environment. So there is no way of using require.

**Comment by galenzhao** [comment]
@mikz thanks

by the way how to add some lib or function to middleware，
I tried put a lua file in same folder as bucket.lua, 
but still can not using it in pipeline,
but I can using in pipeline if by adding a function in bucket.lua file,

**Comment by mikz** [comment]
All the functions available in the middleware are defined in the middleware pipeline sandbox: https://github.com/APItools/monitor/blob/229dc0fd60214df546688f0381ce534df2f55e16/lua/models/pipeline.lua#L243-L266

**Comment by galenzhao** [comment]
thx again,
I still have some problem when adding a lua lib,

I have added this to pipeline.lua

    local complex = require 'complex'
    ....
    
    local env  = {
    console           = console,
    inspect           = inspect,
    complex = complex,
    ....


and add a file complex.lua to the same folder as bucket.lua

    complex = {}
    
    function complex.new (r, i) return {r=r, i=i} end
    
    -- defines a constant `i'
    complex.i = complex.new(0, 1)
    
    function complex.add (c1, c2)
      return complex.new(c1.r + c2.r, c1.i + c2.i)
    end
    
    function complex.sub (c1, c2)
      return complex.new(c1.r - c2.r, c1.i - c2.i)
    end
    
    function complex.mul (c1, c2)
      return complex.new(c1.r*c2.r - c1.i*c2.i,
                         c1.r*c2.i + c1.i*c2.r)
    end
    
    function complex.inv (c)
      local n = c.r^2 + c.i^2
      return complex.new(c.r/n, -c.i/n)
    end
    
    return complex


and the service middleware file

    return function(request, next_middleware)
    -- every middleware has to call next_middleware,
    -- so others have chance to process the request/response
    ....
    local     c = complex.add(complex.i, complex.new(10, 20))

    ....
    -- deal with request
    local response = next_middleware()
    send.notification({msg=response.status, level='info'})
    -- deal with response
    return response
    end

the error log is

{"error":"[string \"test\"]:10: attempt to index global 'complex' (a nil value)"}

**Comment by galenzhao** [comment]
sorry ,
it works,
the file didnt update when deploying,
